services:
  postgres-db:
    image: postgres:18
    container_name: cinema-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - cinema-pg:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - cinema-network

  redis:
    image: redis:7-alpine
    container_name: cinema-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - cinema-network

  minio:
    image: minio/minio:latest
    container_name: cinema-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - cinema-minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - cinema-network

  create-buckets:
    image: minio/mc:latest
    container_name: cinema-create-buckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing local/${S3_BUCKET};
      /usr/bin/mc anonymous set download local/${S3_BUCKET};
      echo 'Buckets created successfully';
      exit 0;
      "
    networks:
      - cinema-network

  django-migrate:
    image: dp-cinema-django
    container_name: cinema-django-migrate
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_ENV: ${DJANGO_ENV}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
    entrypoint: ["python", "manage.py", "migrate", "--noinput"]
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - cinema-network

  flask-migrate:
    image: dp-cinema-flask
    container_name: cinema-flask-migrate
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      DJANGO_INTERNAL_URL: ${DJANGO_INTERNAL_URL}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    command: ["flask", "--app", "main:create_app", "db", "upgrade"]
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - cinema-network

  django:
    image: dp-cinema-django
    build:
      context: ./apps/django_service
      dockerfile: Dockerfile
    container_name: cinema-django
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      FASTAPI_INTERNAL_URL: ${FASTAPI_INTERNAL_URL}
      FLASK_INTERNAL_URL: ${FLASK_INTERNAL_URL}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_ENV: ${DJANGO_ENV}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
    depends_on:
      django-migrate:
        condition: service_completed_successfully
      flask-migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - cinema-network

  flask:
    image: dp-cinema-flask
    build:
      context: ./apps/flask_service
      dockerfile: Dockerfile
    container_name: cinema-flask
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      DJANGO_INTERNAL_URL: ${DJANGO_INTERNAL_URL}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    depends_on:
      django-migrate:
        condition: service_completed_successfully
      flask-migrate:
        condition: service_completed_successfully
      django:
        condition: service_started
    ports:
      - "5001:5001"
    networks:
      - cinema-network

  fastapi:
    build:
      context: ./apps/fastapi_service
      dockerfile: Dockerfile
    container_name: cinema-fastapi
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      DJANGO_INTERNAL_URL: ${DJANGO_INTERNAL_URL}

      REDIS_URL: ${REDIS_URL}

      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
    depends_on:
      django-migrate:
        condition: service_completed_successfully
      flask-migrate:
        condition: service_completed_successfully
      django:
        condition: service_started
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    ports:
      - "8001:8001"
    networks:
      - cinema-network

  worker:
    build:
      context: ./apps/fastapi_service
      dockerfile: Dockerfile.worker
    container_name: cinema-worker
    restart: unless-stopped
    working_dir: /app
    environment:
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
      DJANGO_INTERNAL_URL: ${DJANGO_INTERNAL_URL}

      REDIS_URL: ${REDIS_URL}

      S3_INTERNAL_ENDPOINT: ${S3_INTERNAL_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
    depends_on:
      django-migrate:
        condition: service_completed_successfully
      flask-migrate:
        condition: service_completed_successfully
      django:
        condition: service_started
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    networks:
      - cinema-network

volumes:
  cinema-pg:
  cinema-minio:
  redis-data:

networks:
  cinema-network:
    driver: bridge
