[project]
name = "dp-cinema"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django-filter>=25.2",
    "djangorestframework-stubs>=3.16.8",
    "python-dotenv>=1.2.2",
]

[tool.uv]
managed = true

[tool.uv.workspace]
members = ["apps/django_service", "libs/*"]

[tool.ruff]
src = ["apps", "libs"]
line-length = 88
target-version = "py313"
exclude = ["**/migrations/*.py"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "S", "C90"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "ruff>=0.15.7",
]
