set dotenv-load
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# List recipes
[default]
[private]
default:
    @just --list --unsorted

# Install service dependencies
install:
    uv sync

# Format and fix Python code
fmt:
    uv run ruff format .
    uv run ruff check . --fix

# Check Python code
check:
    uv run ruff format . --check
    uv run ruff check .

# Run local Flask server
run:
    uv run python main.py

# Create migration
migrate message="auto":
    uv run flask --app main:create_app db migrate -m "{{message}}"

# Apply DB migrations
upgrade:
    uv run flask --app main:create_app db upgrade
