# Generated by Django 6.0.3 on 2026-03-31 14:08

import apps.django_service.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.django_service.users.models.ActiveUserManager()),
            ],
        ),
    ]
