set dotenv-load
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# List recipes
[default]
[private]
default:
    @just --list --unsorted

# Install service dependencies
install:
    uv sync

# Format and fix Python code
fmt:
    uv run ruff format .
    uv run ruff check . --fix

# Check Python code
check:
    uv run ruff format . --check
    uv run ruff check .

# Run local API server
run:
    uv run uvicorn main:app --host 0.0.0.0 --port 8001 --reload

# Run Celery worker
worker:
    uv run celery -A core.celery_app:celery_app worker -l info
