# Generated by Django 6.0.4 on 2026-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Review ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(verbose_name='User ID'),
        ),
    ]
