# Generated by Django 6.0.3 on 2026-03-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='created_at',
        ),
    ]
