# Generated by Django 6.0.4 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_watchlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
