# Generated by Django 6.0.4 on 2026-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
