"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = os.environ.get("DJANGO_ENV", "dev").strip().lower()

IS_DEV = DJANGO_ENV == "dev"
IS_PROD = DJANGO_ENV == "prod"

BASE_ENV_FILE = BASE_DIR / ".env"
PROFILE_ENV_FILE = BASE_DIR / f".env.{DJANGO_ENV}"

if BASE_ENV_FILE.exists():
    load_dotenv(BASE_ENV_FILE)

if PROFILE_ENV_FILE.exists():
    load_dotenv(PROFILE_ENV_FILE, override=True)


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-n2!h_$mqsuyp)yf&tqk3bja3$s^shvpnsce6@lef5g@kk!1nmh",
)

if IS_PROD and SECRET_KEY.startswith("django-insecure"):
    raise RuntimeError("DJANGO_SECRET_KEY must be set in production")

DEBUG = (
    os.environ.get("DJANGO_DEBUG", "True" if IS_DEV else "False") == "True"
)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "*" if DEBUG else "",
    ).split(",")
    if host.strip()
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "users.apps.UsersConfig",
    "movies.apps.MoviesConfig",
]

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "cinema_db"),
        "USER": os.environ.get("POSTGRES_USER", "cinema_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "cinema_password"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
AUTH_USER_MODEL = "users.User"

INTERNAL_SERVICE_TOKEN = os.environ.get("INTERNAL_SERVICE_TOKEN")

if IS_PROD and not INTERNAL_SERVICE_TOKEN:
    raise RuntimeError("INTERNAL_SERVICE_TOKEN must be set in production")

S3_INTERNAL_ENDPOINT = os.environ.get("S3_INTERNAL_ENDPOINT", "http://minio:9000")
S3_PUBLIC_ENDPOINT = os.environ.get("S3_PUBLIC_ENDPOINT", "http://localhost:9000")

if os.environ.get("USE_S3", "False") == "True":
    AWS_ACCESS_KEY_ID = os.environ.get("S3_ACCESS_KEY", "minioadmin")
    AWS_SECRET_ACCESS_KEY = os.environ.get("S3_SECRET_KEY", "minioadmin")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("S3_BUCKET", "movies")
    AWS_S3_REGION_NAME = "us-east-1"

    AWS_S3_ENDPOINT_URL = S3_INTERNAL_ENDPOINT

    AWS_S3_USE_SSL = False
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    if S3_PUBLIC_ENDPOINT:
        AWS_S3_CUSTOM_DOMAIN = f"{S3_PUBLIC_ENDPOINT.replace('http://', '').replace('https://', '')}/{AWS_STORAGE_BUCKET_NAME}"
        MEDIA_URL = f"{S3_PUBLIC_ENDPOINT}/{AWS_STORAGE_BUCKET_NAME}/"

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

FASTAPI_SERVICE_URL = os.environ.get("FASTAPI_SERVICE_URL", "http://localhost:8001")

if IS_PROD and not FASTAPI_SERVICE_URL:
    raise RuntimeError("FASTAPI_SERVICE_URL must be set in production")

if IS_PROD and not INTERNAL_SERVICE_TOKEN:
    raise RuntimeError("INTERNAL_SERVICE_TOKEN must be set in production")